#!/bin/bash

if [ "$1" = "" ]; then
	echo -e "\033[1;36mEnter the branch name:\033[0m"
	read branch_name
else
	branch_name="$1"
	echo -e "\033[1;36mCreating branch $branch_name\033[0m"
fi
git checkout -b $branch_name
git push -u origin $branch_name

