#!/bin/bash

branch_name=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
echo -e "\033[1;36m$branch_name\033[0m"

if [ $branch_name == "develop" -o $branch_name == "master" ]; then
  echo -e "\033[1;36mPlease switch to the branch you want to delete and run the script again.\033[0m"
else
  git checkout develop
  git branch -D $branch_name
  git push origin :$branch_name
fi

